name: Scheduled Workflow

on:
  schedule:
    - cron: '01 * * * *'  # Runs at midnight UTC every day

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "This job runs daily at midnight UTC."
